-- Flexoki light palette: https://stephango.com/flexoki
local M = {}

local c = {
  paper = "#FFFCF0",
  base50 = "#F2F0E5",
  base100 = "#E6E4D9",
  base150 = "#DAD8CE",
  base200 = "#CECDC3",
  base300 = "#B7B5AC",
  base600 = "#6F6E69",
  base700 = "#575653",
  ink = "#100F0F",
  red = "#AF3029",
  orange = "#BC5215",
  yellow = "#8E6B01", -- darker yellow for legible text on paper
  green = "#536907", -- darker green for legible text on paper
  cyan = "#1C6C66",
  blue = "#205EA6",
  purple = "#5E409D",
  magenta = "#A02F6F",
  red_bg = "#FFE1D5",
  orange_bg = "#FFE7CE",
  yellow_bg = "#FAEEC6",
  green_bg = "#EDEECF",
  cyan_bg = "#DDF1E4",
  blue_bg = "#E1ECEB",
  purple_bg = "#F0EAEC",
  magenta_bg = "#FEE4E5",
}

M.palette = c
M.options = {}

function M.setup(opts)
  M.options = opts or {}
end

function M.load()
  vim.o.termguicolors = true
  vim.o.background = "light"
  vim.cmd.highlight("clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd.syntax("reset")
  end
  vim.g.colors_name = "flexoki-paper"

  local set = vim.api.nvim_set_hl
  local groups = {
    -- Editor surfaces and navigation
    Normal = { fg = c.ink, bg = c.paper },
    NormalNC = { fg = c.ink, bg = c.paper },
    NormalFloat = { fg = c.ink, bg = c.base50 },
    FloatBorder = { fg = c.base300, bg = c.base50 },
    FloatTitle = { fg = c.blue, bg = c.base50, bold = true },
    FloatFooter = { fg = c.base600, bg = c.base50 },
    WinSeparator = { fg = c.base200 },
    EndOfBuffer = { fg = c.base200 },
    NonText = { fg = c.base300 },
    SpecialKey = { fg = c.base600 },
    Whitespace = { fg = c.base200 },
    LineNr = { fg = c.base600 },
    LineNrAbove = { fg = c.base300 },
    LineNrBelow = { fg = c.base300 },
    CursorLineNr = { fg = c.blue, bold = true },
    CursorLine = { bg = c.base50 },
    CursorColumn = { bg = c.base50 },
    ColorColumn = { bg = c.base50 },
    SignColumn = { bg = c.paper },
    FoldColumn = { fg = c.base600, bg = c.paper },
    Folded = { fg = c.base700, bg = c.base50 },
    VertSplit = { link = "WinSeparator" },
    Visual = { bg = c.base150 },
    VisualNOS = { bg = c.base150 },
    Search = { fg = c.ink, bg = c.yellow_bg },
    IncSearch = { fg = c.paper, bg = c.orange },
    CurSearch = { link = "IncSearch" },
    Substitute = { fg = c.paper, bg = c.red },
    MatchParen = { fg = c.purple, bg = c.purple_bg, bold = true },
    Cursor = { fg = c.paper, bg = c.ink },
    lCursor = { link = "Cursor" },
    TermCursor = { link = "Cursor" },
    Directory = { fg = c.blue },
    Title = { fg = c.blue, bold = true },
    Question = { fg = c.green },
    MoreMsg = { fg = c.green },
    WarningMsg = { fg = c.orange },
    ErrorMsg = { fg = c.red, bold = true },
    ModeMsg = { fg = c.blue, bold = true },
    MsgArea = { fg = c.ink },
    MsgSeparator = { fg = c.base200 },
    StatusLine = { fg = c.ink, bg = c.base100 },
    StatusLineNC = { fg = c.base600, bg = c.base50 },
    TabLine = { fg = c.base600, bg = c.base50 },
    TabLineSel = { fg = c.ink, bg = c.paper, bold = true },
    TabLineFill = { bg = c.base50 },
    WinBar = { fg = c.base700, bg = c.paper },
    WinBarNC = { fg = c.base600, bg = c.paper },
    Pmenu = { fg = c.ink, bg = c.base50 },
    PmenuSel = { fg = c.ink, bg = c.base150, bold = true },
    PmenuSbar = { bg = c.base100 },
    PmenuThumb = { bg = c.base300 },
    PmenuMatch = { fg = c.blue, bold = true },
    PmenuMatchSel = { fg = c.blue, bg = c.base150, bold = true },
    PmenuKind = { fg = c.purple },
    PmenuKindSel = { fg = c.purple, bg = c.base150 },
    PmenuExtra = { fg = c.base600 },
    PmenuExtraSel = { fg = c.base700, bg = c.base150 },
    QuickFixLine = { bg = c.blue_bg, bold = true },
    WildMenu = { fg = c.ink, bg = c.base150 },
    Conceal = { fg = c.base600 },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.blue, undercurl = true },
    SpellRare = { sp = c.purple, undercurl = true },
    SpellLocal = { sp = c.cyan, undercurl = true },

    -- Diff and diagnostics keep their meaning without covering the text.
    DiffAdd = { fg = c.green, bg = c.green_bg },
    DiffChange = { fg = c.blue, bg = c.blue_bg },
    DiffDelete = { fg = c.red, bg = c.red_bg },
    DiffText = { fg = c.blue, bg = c.base150, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.blue },
    Removed = { fg = c.red },
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.orange },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.green },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.red_bg },
    DiagnosticVirtualTextWarn = { fg = c.orange, bg = c.orange_bg },
    DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.blue_bg },
    DiagnosticVirtualTextHint = { fg = c.cyan, bg = c.cyan_bg },
    DiagnosticVirtualTextOk = { fg = c.green, bg = c.green_bg },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticSignError = { link = "DiagnosticError" },
    DiagnosticSignWarn = { link = "DiagnosticWarn" },
    DiagnosticSignInfo = { link = "DiagnosticInfo" },
    DiagnosticSignHint = { link = "DiagnosticHint" },
    DiagnosticSignOk = { link = "DiagnosticOk" },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
    DiagnosticUnnecessary = { fg = c.base600 },
    DiagnosticDeprecated = { sp = c.orange, strikethrough = true },
    LspReferenceText = { bg = c.base100 },
    LspReferenceRead = { bg = c.base100 },
    LspReferenceWrite = { bg = c.blue_bg },
    LspSignatureActiveParameter = { fg = c.blue, bold = true },
    LspInlayHint = { fg = c.base600, bg = c.base50 },
    LspCodeLens = { fg = c.base600 },
    LspCodeLensSeparator = { fg = c.base300 },

    -- Traditional syntax and Tree-sitter captures share one vocabulary.
    Comment = { fg = c.base600, italic = true },
    Constant = { fg = c.yellow },
    String = { fg = c.cyan },
    Character = { fg = c.cyan },
    Number = { fg = c.purple },
    Boolean = { fg = c.purple },
    Float = { fg = c.purple },
    Identifier = { fg = c.blue },
    Function = { fg = c.orange },
    Statement = { fg = c.green },
    Conditional = { fg = c.green },
    Repeat = { fg = c.green },
    Label = { fg = c.green },
    Operator = { fg = c.base700 },
    Keyword = { fg = c.green },
    Exception = { fg = c.red },
    PreProc = { fg = c.magenta },
    Include = { fg = c.red },
    Define = { fg = c.magenta },
    Macro = { fg = c.magenta },
    Type = { fg = c.magenta },
    StorageClass = { fg = c.magenta },
    Structure = { fg = c.magenta },
    Typedef = { fg = c.magenta },
    Special = { fg = c.orange },
    SpecialChar = { fg = c.magenta },
    Tag = { fg = c.red },
    Delimiter = { fg = c.base700 },
    SpecialComment = { fg = c.base600, italic = true },
    Underlined = { fg = c.blue, underline = true },
    Ignore = { fg = c.base600 },
    Error = { fg = c.red, bg = c.red_bg },
    Todo = { fg = c.ink, bg = c.yellow_bg, bold = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = c.base700, italic = true },
    ["@comment.error"] = { fg = c.red, bold = true },
    ["@comment.warning"] = { fg = c.orange, bold = true },
    ["@comment.todo"] = { link = "Todo" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.purple },
    ["@constant.macro"] = { fg = c.magenta },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.magenta },
    ["@string.special"] = { fg = c.magenta },
    ["@string.special.url"] = { fg = c.blue, underline = true },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.orange },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { fg = c.magenta },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { fg = c.orange },
    ["@parameter"] = { fg = c.blue },
    ["@variable"] = { fg = c.blue },
    ["@variable.builtin"] = { fg = c.magenta },
    ["@variable.parameter"] = { fg = c.blue },
    ["@variable.member"] = { fg = c.blue },
    ["@property"] = { fg = c.blue },
    ["@field"] = { fg = c.blue },
    ["@attribute"] = { fg = c.blue },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.magenta },
    ["@type.definition"] = { fg = c.magenta },
    ["@module"] = { fg = c.red },
    ["@namespace"] = { fg = c.red },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.green },
    ["@keyword.return"] = { fg = c.green },
    ["@keyword.import"] = { fg = c.red },
    ["@keyword.exception"] = { fg = c.red },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { fg = c.base700 },
    ["@punctuation.bracket"] = { fg = c.base700 },
    ["@punctuation.special"] = { fg = c.magenta },
    ["@tag"] = { fg = c.red },
    ["@tag.attribute"] = { fg = c.blue },
    ["@tag.delimiter"] = { fg = c.base700 },
    ["@markup.heading"] = { fg = c.blue, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.raw"] = { fg = c.cyan },
    ["@markup.link"] = { fg = c.blue, underline = true },
    ["@markup.link.url"] = { fg = c.blue, underline = true },
    ["@markup.link.label"] = { fg = c.blue },
    ["@markup.list"] = { fg = c.orange },
    ["@markup.quote"] = { fg = c.base700, italic = true },
    ["@markup.math"] = { fg = c.purple },
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.string"] = { link = "String" },
    ["@lsp.type.number"] = { link = "Number" },
    ["@lsp.type.keyword"] = { link = "Keyword" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.parameter"] = { fg = c.blue },
    ["@lsp.type.property"] = { fg = c.blue },
    ["@lsp.type.variable"] = { fg = c.blue },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.namespace"] = { fg = c.red },

    -- Plugins in this config and common LazyVim UI components.
    BlinkCmpMenu = { fg = c.ink, bg = c.base50 },
    BlinkCmpMenuBorder = { fg = c.base300, bg = c.base50 },
    BlinkCmpMenuSelection = { fg = c.ink, bg = c.base150, bold = true },
    BlinkCmpLabel = { fg = c.ink },
    BlinkCmpLabelMatch = { fg = c.blue, bold = true },
    BlinkCmpLabelDescription = { fg = c.base600 },
    BlinkCmpKind = { fg = c.purple },
    BlinkCmpSource = { fg = c.base600 },
    BlinkCmpDoc = { fg = c.ink, bg = c.base50 },
    BlinkCmpDocBorder = { fg = c.base300, bg = c.base50 },
    BlinkCmpSignatureHelp = { fg = c.ink, bg = c.base50 },
    BlinkCmpSignatureHelpBorder = { fg = c.base300, bg = c.base50 },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.blue, bold = true },
    BlinkCmpDocSeparator = { fg = c.base200, bg = c.base50 },
    BlinkCmpGhostText = { fg = c.base600 },
    FzfLuaNormal = { fg = c.ink, bg = c.base50 },
    FzfLuaBorder = { fg = c.base300, bg = c.base50 },
    FzfLuaTitle = { fg = c.blue, bg = c.base50, bold = true },
    FzfLuaPreviewNormal = { fg = c.ink, bg = c.base50 },
    FzfLuaPreviewBorder = { fg = c.base300, bg = c.base50 },
    FzfLuaCursorLine = { bg = c.base150 },
    FzfLuaDirPart = { fg = c.base600 },
    FzfLuaFilePart = { fg = c.ink },
    FzfLuaHeaderBind = { fg = c.blue, bold = true },
    FzfLuaHeaderText = { fg = c.base700 },
    FzfLuaPathColNr = { fg = c.base600 },
    FzfLuaPathLineNr = { fg = c.blue },
    FzfLuaLivePrompt = { fg = c.blue },
    FzfLuaLiveSym = { fg = c.blue },
    FzfLuaBufNr = { fg = c.purple },
    FzfLuaBufFlagCur = { fg = c.green },
    FzfLuaBufFlagAlt = { fg = c.base600 },
    FzfLuaTabTitle = { fg = c.blue, bold = true },
    FzfLuaTabMarker = { fg = c.green, bold = true },
    FzfLuaFzfNormal = { fg = c.ink, bg = c.base50 },
    FzfLuaFzfCursorLine = { fg = c.ink, bg = c.base150 },
    FzfLuaFzfMatch = { fg = c.blue, bold = true },
    FzfLuaFzfBorder = { fg = c.base300, bg = c.base50 },
    FzfLuaFzfGutter = { bg = c.base50 },
    FzfLuaFzfHeader = { fg = c.base700 },
    FzfLuaFzfInfo = { fg = c.base600 },
    FzfLuaFzfPointer = { fg = c.orange, bold = true },
    FzfLuaFzfPrompt = { fg = c.blue, bold = true },
    FzfLuaFzfQuery = { fg = c.ink },
    SnacksPicker = { fg = c.ink, bg = c.base50 },
    SnacksPickerBorder = { fg = c.base300, bg = c.base50 },
    SnacksPickerTitle = { fg = c.blue, bg = c.base50, bold = true },
    SnacksPickerMatch = { fg = c.blue, bold = true },
    SnacksPickerSelected = { fg = c.blue, bold = true },
    SnacksPickerDir = { fg = c.base600 },
    SnacksPickerPathHidden = { fg = c.base600 },
    SnacksPickerPrompt = { fg = c.blue },
    SnacksPickerDirectory = { fg = c.blue },
    SnacksPickerFile = { fg = c.ink },
    SnacksPickerPathIgnored = { fg = c.base600 },
    SnacksPickerSearch = { fg = c.ink, bg = c.yellow_bg },
    SnacksPickerPreviewCursorLine = { bg = c.base100 },
    SnacksPickerRow = { fg = c.blue },
    SnacksPickerCol = { fg = c.base600 },
    SnacksInput = { fg = c.ink, bg = c.base50 },
    SnacksInputBorder = { fg = c.base300, bg = c.base50 },
    SnacksNotifierInfo = { fg = c.blue },
    SnacksNotifierWarn = { fg = c.orange },
    SnacksNotifierError = { fg = c.red },
    SnacksNotifierDebug = { fg = c.purple },
    SnacksNotifierTrace = { fg = c.base600 },
    NoiceCmdlinePopup = { fg = c.ink, bg = c.base50 },
    NoiceCmdlinePopupBorder = { fg = c.blue, bg = c.base50 },
    NoiceCmdlineIcon = { fg = c.blue },
    NoiceFormatProgressDone = { fg = c.paper, bg = c.green },
    NoiceFormatProgressTodo = { fg = c.base700, bg = c.base100 },
    WhichKey = { fg = c.blue },
    WhichKeyDesc = { fg = c.ink },
    WhichKeyGroup = { fg = c.magenta },
    WhichKeySeparator = { fg = c.base600 },
    NeoTreeNormal = { fg = c.ink, bg = c.base50 },
    NeoTreeNormalNC = { fg = c.ink, bg = c.base50 },
    NeoTreeWinSeparator = { fg = c.base200, bg = c.base50 },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeDirectoryIcon = { fg = c.blue },
    NeoTreeGitAdded = { fg = c.green },
    NeoTreeGitModified = { fg = c.orange },
    NeoTreeGitDeleted = { fg = c.red },
    NeoTreeGitConflict = { fg = c.magenta },
    NeoTreeGitIgnored = { fg = c.base600 },
    NeoTreeGitRenamed = { fg = c.blue },
    NeoTreeGitStaged = { fg = c.green },
    NeoTreeGitUntracked = { fg = c.green },
    NeoTreeGitUnstaged = { fg = c.orange },
    NeoTreeDotfile = { fg = c.base600 },
    NeoTreeIndentMarker = { fg = c.base200 },
    NeoTreeFileNameOpened = { fg = c.blue, bold = true },
    NeoTreeFloatNormal = { fg = c.ink, bg = c.base50 },
    NeoTreeFloatBorder = { fg = c.base300, bg = c.base50 },
    NeoTreeFloatTitle = { fg = c.blue, bg = c.base50, bold = true },
    NeoTreeRootName = { fg = c.blue, bold = true },
    NeoTreeCursorLine = { bg = c.base100 },
    NeoTreeSelected = { fg = c.blue, bg = c.blue_bg },
    NeoTreeSignColumn = { bg = c.base50 },
    NeoTreeEndOfBuffer = { fg = c.base200, bg = c.base50 },
    RenderMarkdownCode = { bg = c.base50 },
    RenderMarkdownCodeInline = { fg = c.cyan, bg = c.base50 },
    RenderMarkdownQuote = { fg = c.base600 },
    RenderMarkdownBullet = { fg = c.orange },
    RenderMarkdownDash = { fg = c.base300 },
    RenderMarkdownTableHead = { fg = c.blue },
    RenderMarkdownTableRow = { fg = c.base300 },
    RenderMarkdownLink = { fg = c.blue, underline = true },
    RenderMarkdownChecked = { fg = c.green },
    RenderMarkdownUnchecked = { fg = c.base600 },
    RenderMarkdownTodo = { fg = c.orange },
    RenderMarkdownH1 = { fg = c.blue, bold = true },
    RenderMarkdownH2 = { fg = c.magenta, bold = true },
    RenderMarkdownH3 = { fg = c.green, bold = true },
    RenderMarkdownH4 = { fg = c.orange, bold = true },
    RenderMarkdownH5 = { fg = c.purple, bold = true },
    RenderMarkdownH6 = { fg = c.cyan, bold = true },
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.orange },
    GitSignsDelete = { fg = c.red },
    MiniDiffSignAdd = { fg = c.green },
    MiniDiffSignChange = { fg = c.orange },
    MiniDiffSignDelete = { fg = c.red },
    BufferLineFill = { bg = c.base50 },
    BufferLineBackground = { fg = c.base600, bg = c.base50 },
    BufferLineBufferVisible = { fg = c.base700, bg = c.base50 },
    BufferLineBufferSelected = { fg = c.ink, bg = c.paper, bold = true },
    BufferLineIndicatorSelected = { fg = c.blue, bg = c.paper },
    BufferLineSeparator = { fg = c.base200, bg = c.base50 },
    BufferLineSeparatorVisible = { fg = c.base200, bg = c.base50 },
    BufferLineSeparatorSelected = { fg = c.base200, bg = c.paper },
    BufferLineModified = { fg = c.orange, bg = c.base50 },
    BufferLineModifiedVisible = { fg = c.orange, bg = c.base50 },
    BufferLineModifiedSelected = { fg = c.orange, bg = c.paper },
    BufferLineTab = { fg = c.base600, bg = c.base50 },
    BufferLineTabSelected = { fg = c.blue, bg = c.paper, bold = true },
    BufferLineCloseButton = { fg = c.base600, bg = c.base50 },
    BufferLineCloseButtonSelected = { fg = c.base700, bg = c.paper },
    BufferLineError = { fg = c.red, bg = c.base50 },
    BufferLineErrorSelected = { fg = c.red, bg = c.paper },
    BufferLineWarning = { fg = c.orange, bg = c.base50 },
    BufferLineWarningSelected = { fg = c.orange, bg = c.paper },
    BufferLineInfo = { fg = c.blue, bg = c.base50 },
    BufferLineInfoSelected = { fg = c.blue, bg = c.paper },
    BufferLineHint = { fg = c.cyan, bg = c.base50 },
    BufferLineHintSelected = { fg = c.cyan, bg = c.paper },
    TroubleNormal = { fg = c.ink, bg = c.base50 },
    TroubleNormalNC = { fg = c.ink, bg = c.base50 },
    TroubleCount = { fg = c.blue, bg = c.blue_bg },
    TroubleFilename = { fg = c.ink },
    TroubleDirectory = { fg = c.base600 },
    TroubleText = { fg = c.base700 },
    TroubleSource = { fg = c.base600 },
    TroublePos = { fg = c.blue },
    TroublePreview = { bg = c.blue_bg },
    TroubleIndent = { fg = c.base200 },
    DapBreakpoint = { fg = c.red },
    DapBreakpointCondition = { fg = c.orange },
    DapBreakpointRejected = { fg = c.base600 },
    DapLogPoint = { fg = c.blue },
    DapStopped = { fg = c.green },
    DapStoppedLine = { bg = c.green_bg },
    DapUINormal = { fg = c.ink, bg = c.base50 },
    DapUIFloatNormal = { fg = c.ink, bg = c.base50 },
    DapUIFloatBorder = { fg = c.base300, bg = c.base50 },
    DapUIScope = { fg = c.blue, bold = true },
    DapUIType = { fg = c.magenta },
    DapUIValue = { fg = c.ink },
    DapUIModifiedValue = { fg = c.orange, bold = true },
    DapUIThread = { fg = c.blue },
    DapUIStoppedThread = { fg = c.green, bold = true },
    DapUIWatchesError = { fg = c.red },
    DapUIBreakpointsInfo = { fg = c.green },
    DapUIBreakpointsCurrentLine = { fg = c.blue, bold = true },
    DapUIStepOver = { fg = c.blue },
    DapUIStepInto = { fg = c.blue },
    DapUIStepBack = { fg = c.blue },
    DapUIStepOut = { fg = c.blue },
    DapUIStop = { fg = c.red },
    DapUIPlayPause = { fg = c.green },
    DapUIRestart = { fg = c.green },
    NvimDapVirtualText = { fg = c.base600 },
    NvimDapVirtualTextChanged = { fg = c.orange, bg = c.orange_bg },
    NvimDapVirtualTextError = { fg = c.red, bg = c.red_bg },
    NvimDapVirtualTextInfo = { fg = c.blue, bg = c.blue_bg },
    GrugFarResultsChangeIndicator = { fg = c.orange },
    GrugFarResultsRemoveIndicator = { fg = c.red },
    GrugFarResultsAddIndicator = { fg = c.green },
    GrugFarResultsPath = { fg = c.blue, underline = true },
    GrugFarResultsMatch = { fg = c.blue, bg = c.blue_bg, bold = true },
    GrugFarCurrentMatch = { fg = c.ink, bg = c.yellow_bg, bold = true },
    LazyNormal = { fg = c.ink, bg = c.base50 },
    LazyButton = { fg = c.ink, bg = c.base100 },
    LazyButtonActive = { fg = c.paper, bg = c.blue, bold = true },
    MasonNormal = { fg = c.ink, bg = c.base50 },
    FlashLabel = { fg = c.paper, bg = c.red, bold = true },
    FlashMatch = { fg = c.blue, bg = c.blue_bg },
    FlashCurrent = { fg = c.red, bg = c.red_bg },
  }

  for name, spec in pairs(groups) do
    set(0, name, spec)
  end

  local overrides = M.options.highlights or {}
  local function resolve(name, visiting)
    assert(not visiting[name], "Circular highlight link in overrides: " .. name)
    visiting[name] = true
    local base = groups[name] or vim.api.nvim_get_hl(0, { name = name })
    local override = overrides[name] or {}
    if override.link then
      override = { link = override.link }
    end
    local link = override.link or base.link
    if link then
      base = resolve(link, visiting)
    end
    local result = vim.tbl_extend("force", base, override)
    result.link = nil
    visiting[name] = nil
    return result
  end

  -- Resolve before applying so linked overrides do not depend on iteration order.
  local resolved = {}
  for name, spec in pairs(overrides) do
    resolved[name] = spec.link and { link = spec.link } or resolve(name, {})
  end
  for name, spec in pairs(resolved) do
    set(0, name, spec)
  end

  local terminal = {
    c.ink, c.red, c.green, c.yellow, c.blue, c.magenta, c.cyan, c.base700,
    c.base600, "#D14D41", "#879A39", "#D0A215", "#4385BE", "#CE5D97", "#3AA99F", c.paper,
  }
  for i, color in ipairs(terminal) do
    vim.g["terminal_color_" .. (i - 1)] = color
  end
end

return M
